language: node_js
node_js:
  - 12.0.0

cache:
  directories:
    - node_modules

global:
  - export NODE_ENV=test

addons:
  postgresql: "12.1"

services:
  - postgresql

env:
  global:
    - CC_TEST_REPORTER_ID=b9ac81adddde6a79f50181296a3cb7afb9113b60deb543242857e745fab6111b

before_install:
  - yarn

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - yarn build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - yarn coverage
script:
  - yarn test
